apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: docker-registry
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: master
          image: k8s.gcr.io/redis
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 200m
              memory: 1000Mi # increase the limit memory for to cache more ojbects
            requests:
              cpu: 100m
              memory: 500Mi 
